version: '3.8'

services:
  app:
    build:
      context: .
      target: local
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - LOG_LEVEL=INFO
